### PR TITLE
Issue 7: Correctly handles blank and comment only files

### PR DESCRIPTION
**Pull request by scuml**

### CODE REVIEW

**Comment by scuml** [comment]
Fix for #7

**Comment by scuml** [comment]
Someone able to review and merge?

**Comment by laktak** [comment]
Thanks for your help!

**Comment by sonnyvan** [comment]
Omg, this is awesome. Thanks @scuml

**Comment by sonnyvan** [comment]
@laktak could we please get this fix onto PyPI?

**Comment by laktak** [comment]
Yes, I've pushed 2.0.7 to pypi.

**Comment by sonnyvan** [comment]
Thank you @laktak and @scuml

**Comment by scuml** [comment]
@laktak Thanks for pushing to pypi!

**Pull request merged**
